{
  "branches": {
    "only": [
      "master"
    ]
  },
  "cache": "pip",
  "dist": "focal",
  "git": {
    "submodules": false
  },
  "install": [
    ". scripts/travis-install.sh",
    "make -e install-$BUILD"
  ],
  "language": "python",
  "matrix": {
    "fast_finish": true,
    "include": [
      {
        "env": "BUILD=style",
        "python": "3.7"
      },
      {
        "env": "BUILD=test REQUIREMENTS=release",
        "python": "3.7"
      },
      {
        "env": "BUILD=test-storage DAV_SERVER=radicale REQUIREMENTS=release ",
        "python": "3.7"
      },
      {
        "env": "BUILD=test-storage DAV_SERVER=xandikos REQUIREMENTS=release ",
        "python": "3.7"
      },
      {
        "env": "BUILD=test-storage DAV_SERVER=fastmail REQUIREMENTS=release ",
        "python": "3.7"
      },
      {
        "env": "BUILD=test REQUIREMENTS=minimal",
        "python": "3.7"
      },
      {
        "env": "BUILD=test-storage DAV_SERVER=radicale REQUIREMENTS=minimal ",
        "python": "3.7"
      },
      {
        "env": "BUILD=test-storage DAV_SERVER=xandikos REQUIREMENTS=minimal ",
        "python": "3.7"
      },
      {
        "env": "BUILD=test REQUIREMENTS=release",
        "python": "3.8"
      },
      {
        "env": "BUILD=test-storage DAV_SERVER=radicale REQUIREMENTS=release ",
        "python": "3.8"
      },
      {
        "env": "BUILD=test-storage DAV_SERVER=xandikos REQUIREMENTS=release ",
        "python": "3.8"
      },
      {
        "env": "BUILD=test REQUIREMENTS=minimal",
        "python": "3.8"
      },
      {
        "env": "BUILD=test-storage DAV_SERVER=radicale REQUIREMENTS=minimal ",
        "python": "3.8"
      },
      {
        "env": "BUILD=test-storage DAV_SERVER=xandikos REQUIREMENTS=minimal ",
        "python": "3.8"
      },
      {
        "env": "BUILD=test REQUIREMENTS=release",
        "python": "3.9"
      },
      {
        "env": "BUILD=test-storage DAV_SERVER=radicale REQUIREMENTS=release ",
        "python": "3.9"
      },
      {
        "env": "BUILD=test-storage DAV_SERVER=xandikos REQUIREMENTS=release ",
        "python": "3.9"
      },
      {
        "env": "BUILD=test REQUIREMENTS=minimal",
        "python": "3.9"
      },
      {
        "env": "BUILD=test-storage DAV_SERVER=radicale REQUIREMENTS=minimal ",
        "python": "3.9"
      },
      {
        "env": "BUILD=test-storage DAV_SERVER=xandikos REQUIREMENTS=minimal ",
        "python": "3.9"
      },
      {
        "env": "BUILD=test ETESYNC_TESTS=true REQUIREMENTS=latest",
        "python": "3.7"
      }
    ]
  },
  "script": [
    "make -e $BUILD"
  ],
  "services": [
    "docker"
  ],
  "sudo": true
}